config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'welcome' => 'pages#welcome'

  resources :tasks, only: [:new, :create, :show, :index, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true
  validates :due_date, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    if task.save
      redirect_to(task)
    else
      flash["There was an error creating the task!"]
    end
  end

  def show
    id = params[:id]
    @task = Task.find(id)
  end

  def index
    @tasks = Task.all
  end

  def update
    id = params[:id]
    task = Task.find(id)
    task.assign_attributes(completed: true)
    if task.save
      redirect_to(task)
    else
      flash["There was an error updating the task!"]
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :due_date, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="centered_layout_container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/welcome.html.erb
<%= link_to "New Task", new_task_path %>

app/views/tasks/index.html.erb
<% @tasks.each do |task| %>

  <div class="task_container">
    <span>Name: </span><%= task.name %><br />
    <span>Due Date: </span><%= task.due_date %><br />
    <span>Description: </span><%= task.description %><br/>

    <% if task.completed? %>
      <span>This task has been completed!</span>
    <% else %>
      <span>This task has not yet been completed.</span>
    <% end %>
  </div>

<% end %>

app/views/tasks/new.html.erb
<%= form_for @task do |f| %>
  <div class="form_label_and_field">
    <%= f.label "name", {class: "label"} %>
    <%= f.text_field "name", {class: "field_small"} %><br/>
  </div>

  <div class="form_label_and_field">
    <%= f.label "due_date", {class: "label"} %>
    <%= f.text_field "due_date", {class: "field_small"} %><br/>
  </div>

  <div class="form_label_and_field">
    <%= f.label "description", {class: "label"} %>
    <%= f.text_area "description", {class: "field_large"} %><br/>
  </div>

  <div class="centered_button_container">
    <%= f.submit %>
  </div>
<% end  %>

app/views/tasks/show.html.erb
<%=  link_to "Show All Tasks", tasks_path %><br/>

<div class="task_container">
  <span>Name: </span><%= @task.name %><br />
  <span>Due Date: </span><%= @task.due_date %><br />
  <span>Description: </span><%= @task.description %><br/>

  <% if @task.completed? %>
    <span>This task has been completed!</span>
  <% else %>
    <span>This task has not yet been completed.</span>
    <%= link_to "Mark Task as Completed", task_path(@task.id), method: :put %>
  <% end %><br/>
</div>